version: "2017-09-20"
schedule: "0 10 * * *"  # At 10:00 AM UTC on every day

tags:
  application: agentic-identity-broker

shared-env: &shared-env
  APPLICATION: agentic-identity-broker
  COMPONENT: email-address-insights
  VERSION: "#{CDP_BUILD_VERSION}"
  IMAGE: "customer-iam/eai:#{CDP_BUILD_VERSION}"

notifications:
  - channel: google_chat
    rooms:
      - "AAAAhi4vo1w"
    config:
      emoji_pack: emotional
    conditions:
      # Do not Notify on nothing
      - notify: false
      # Do not notify on FAILED pull request builds
      - notify: false
        entity: pipeline_step
        step_type: script
        status: FAILED
        event: pull_request
      # Notify on other FAILED builds
      - notify: true
        step_type: script
        status: [FAILED, ERROR]
      # Notify on FAILED deploys
      - notify: true
        step_type: deploy
        status: [FAILED, ERROR]

pipeline:
  - id: test
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/go-1.25.5
    commands:
      - desc: "Lint"
        cmd: |
          make lint
      - desc: "Test"
        cmd: |
          make test

  - id: build
    type: script
    when:
      - event: push
        branch: main
      - event: schedule
    vm_config:
      type: linux
      image: cdp-runtime/go-1.25.5
    cache:
      paths:
        # pkg cache for Go modules and Go build cache
        - /go/pkg/mod
        - ~/.cache/go-build
    commands:
      - desc: prepare
        cmd: |
          make init
      - desc: build
        cmd: |
          make build.local
      - desc: push-multiarch
        cmd: |
          # build and push image to ZCR
          VERSION="${CDP_BUILD_VERSION}" make push-multiarch

          # promote image to a production during push/merge pipeline
          cdp-promote-image ${CDP_REGISTRY}/customer-iam/eai:${CDP_BUILD_VERSION}
      - desc: git-tag
        cmd: |
          git gh-tag "${CDP_BUILD_VERSION}"

  - id: eai-test-deployment
    type: deploy
    target: customer-iam-test
    when:
      - event: push
        branch: main
      - event: schedule
    sources:
      - dir: deploy/main/apply
        template_vars:
          <<: *shared-env
          ENVIRONMENT: "testing"
          MIN_REPLICAS: "1"
          MAX_REPLICAS: "1"

  - id: testing-100
    type: traffic
    target: customer-iam-test
    stackset: email-address-insights
    stack_version: "#{CDP_BUILD_VERSION}"
    target_percentage: 100
    when:
      - event: push
        branch: main
      - event: schedule

  - id: eai-prod-deployment
    type: deploy
    target: customer-iam
    requires_human_approval: false
    when:
      - event: push
        branch: main
      - event: schedule
    sources:
      - dir: deploy/main/apply
        template_vars:
          <<: *shared-env
          ENVIRONMENT: "production"
          MIN_REPLICAS: "3"
          MAX_REPLICAS: "10"

  - id: prod-100
    type: traffic
    target: customer-iam
    stackset: email-address-insights
    stack_version: "#{CDP_BUILD_VERSION}"
    target_percentage: 100
    requires_human_approval: false
    when:
      - event: push
        branch: main
      - event: schedule
