// Code generated by gen_ids.go; DO NOT EDIT.
package id

import (
	"database/sql/driver"
	"encoding/json"

	"github.com/google/uuid"
)

// AgentID uniquely identifies a agent entity.
type AgentID uuid.UUID

func NewAgentID() AgentID                       { return AgentID(uuid.New()) }
func ParseAgentID(s string) (AgentID, error)    { id, err := uuid.Parse(s); return AgentID(id), err }
func MustParseAgentID(s string) AgentID         { return AgentID(uuid.MustParse(s)) }
func (id AgentID) String() string               { return uuid.UUID(id).String() }
func (id AgentID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id AgentID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *AgentID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = AgentID(parsed)
	return nil
}
func (id AgentID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *AgentID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id AgentID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *AgentID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// ServiceID uniquely identifies a service entity.
type ServiceID uuid.UUID

func NewServiceID() ServiceID                     { return ServiceID(uuid.New()) }
func ParseServiceID(s string) (ServiceID, error)  { id, err := uuid.Parse(s); return ServiceID(id), err }
func MustParseServiceID(s string) ServiceID       { return ServiceID(uuid.MustParse(s)) }
func (id ServiceID) String() string               { return uuid.UUID(id).String() }
func (id ServiceID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id ServiceID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *ServiceID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = ServiceID(parsed)
	return nil
}
func (id ServiceID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *ServiceID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id ServiceID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *ServiceID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// GrantID uniquely identifies a grant entity.
type GrantID uuid.UUID

func NewGrantID() GrantID                       { return GrantID(uuid.New()) }
func ParseGrantID(s string) (GrantID, error)    { id, err := uuid.Parse(s); return GrantID(id), err }
func MustParseGrantID(s string) GrantID         { return GrantID(uuid.MustParse(s)) }
func (id GrantID) String() string               { return uuid.UUID(id).String() }
func (id GrantID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id GrantID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *GrantID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = GrantID(parsed)
	return nil
}
func (id GrantID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *GrantID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id GrantID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *GrantID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// SessionID uniquely identifies a session entity.
type SessionID uuid.UUID

func NewSessionID() SessionID                     { return SessionID(uuid.New()) }
func ParseSessionID(s string) (SessionID, error)  { id, err := uuid.Parse(s); return SessionID(id), err }
func MustParseSessionID(s string) SessionID       { return SessionID(uuid.MustParse(s)) }
func (id SessionID) String() string               { return uuid.UUID(id).String() }
func (id SessionID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id SessionID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *SessionID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = SessionID(parsed)
	return nil
}
func (id SessionID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *SessionID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id SessionID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *SessionID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// UserID uniquely identifies a user entity.
type UserID uuid.UUID

func NewUserID() UserID                        { return UserID(uuid.New()) }
func ParseUserID(s string) (UserID, error)     { id, err := uuid.Parse(s); return UserID(id), err }
func MustParseUserID(s string) UserID          { return UserID(uuid.MustParse(s)) }
func (id UserID) String() string               { return uuid.UUID(id).String() }
func (id UserID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id UserID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *UserID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = UserID(parsed)
	return nil
}
func (id UserID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *UserID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id UserID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *UserID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }
