{{- if .Values.broker.thirdPartyOauth2.jweSigningKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentic-identity-broker.fullname" . }}-jwe-key
  labels:
    {{- include "agentic-identity-broker.labels" . | nindent 4 }}
type: Opaque
data:
  signing-key: {{ .Values.broker.thirdPartyOauth2.jweSigningKey | b64enc | quote }}
{{- end }}
