{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentic-identity-broker.serviceAccountName" . }}
  labels:
    {{- include "agentic-identity-broker.labels" . | nindent 4 }}
  {{- $irsa := dict }}
  {{- if .Values.serviceAccount.irsa.enabled }}
  {{- $irsa = dict "iam.amazonaws.com/role" .Values.serviceAccount.irsa.role }}
  {{- end }}
  {{- $annotations := merge (.Values.serviceAccount.annotations | default dict) $irsa }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
