apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentic-identity-broker.fullname" . }}
  labels:
    {{- include "agentic-identity-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.enduser }}
    targetPort: enduser
    protocol: TCP
    name: enduser
  - port: {{ .Values.service.ports.admin }}
    targetPort: admin
    protocol: TCP
    name: admin
  selector:
    {{- include "agentic-identity-broker.selectorLabels" . | nindent 4 }}
