{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentic-identity-broker.serviceAccountName" . }}
  labels:
    {{- include "agentic-identity-broker.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.irsa.enabled }}
  annotations:
    iam.amazonaws.com/role: {{ .Values.serviceAccount.irsa.roleArn | quote }}
  {{- else if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
