package storage

import (
	"time"

	"github.com/agentic-identity-broker/agentic-identity-broker/internal/domain/id"
)

// BrokerClientCredential represents OAuth2 client credentials generated by the broker
// and bound to exactly one Agent. ClientID equals the agent's UUID string, making a
// separate AgentID field redundant. Lifecycle: created on demand via Admin API,
// replaced atomically on rotation, cascade-deleted when the associated Agent is deleted.
type BrokerClientCredential struct {
	ID         id.CredentialID `json:"id" db:"id"`
	ClientID   id.ClientID     `json:"client_id" db:"client_id"`
	SecretHash string          `json:"-" db:"secret_hash"` // Never serialize
	CreatedAt  time.Time       `json:"created_at" db:"created_at"`
	RotatedAt  *time.Time      `json:"rotated_at,omitempty" db:"rotated_at"`
}

// Validate validates the BrokerClientCredential fields.
func (c *BrokerClientCredential) Validate() error {
	if c.ClientID.IsZero() {
		return NewStorageError("BrokerClientCredential.Validate", ErrorKindValidation, nil, "client_id is required")
	}
	if c.SecretHash == "" {
		return NewStorageError("BrokerClientCredential.Validate", ErrorKindValidation, nil, "secret_hash is required")
	}
	return nil
}
