package model

import (
	"errors"
	"fmt"
	"net/url"
	"time"
)

// isAllowedHTTPSScheme checks if a URL uses an allowed scheme.
// HTTPS is always allowed. HTTP is only allowed for localhost addresses
// or when skipHTTPSValidation is true (dev/test mode).
func isAllowedHTTPSScheme(urlStr string, skipHTTPSValidation bool) bool {
	parsed, err := url.Parse(urlStr)
	if err != nil {
		return false
	}
	if parsed.Scheme == "https" {
		return true
	}
	if parsed.Scheme == "http" {
		if skipHTTPSValidation {
			return true
		}
		host := parsed.Hostname()
		return host == "localhost" || host == "127.0.0.1" || host == "::1"
	}
	return false
}

// ThirdpartyOAuth2ProviderEntity is the domain entity for an external OAuth2 provider that
// agents can access on behalf of users (e.g., GitHub, Google, Databricks).
//
// The Secret field uses the Secret value object with two mutually exclusive states:
//   - Plaintext state: used when creating/updating a provider, and when returned from Get/List
//     (the domain service decrypts the raw ciphertext before returning the entity to callers).
//   - Encrypted state: used internally by the repository layer. Callers (handlers, other domain
//     services) never observe an entity in encrypted state.
//
// Encryption and decryption happens exclusively in domain services, not in this entity.
type ThirdpartyOAuth2ProviderEntity struct {
	ID                  string
	DisplayName         string
	ClientID            string
	Secret              Secret
	IssuerURI           string
	Discovery           DiscoveryConfig
	Endpoints           OAuth2Endpoints
	Scopes              []OAuthScope
	ProtectedResources  []string
	ServiceRequirements []ServiceRequirement
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Validate performs basic validation on the entity.
// It checks that required fields are present and the secret is in a valid state.
func (e *ThirdpartyOAuth2ProviderEntity) Validate() error {
	if e.ID == "" {
		return errors.New("provider ID cannot be empty")
	}
	if e.DisplayName == "" {
		return errors.New("display_name is required")
	}
	if len(e.DisplayName) > 255 {
		return errors.New("display_name exceeds 255 characters")
	}
	if e.ClientID == "" {
		return errors.New("client_id is required")
	}

	// Secret must be in a valid state (either plaintext or encrypted)
	if e.Secret.IsPlaintext() {
		if _, err := e.Secret.GetPlaintext(); err != nil {
			return err
		}
	} else if e.Secret.IsEncrypted() {
		if _, err := e.Secret.GetCiphertext(); err != nil {
			return err
		}
	}

	if e.IssuerURI == "" {
		return errors.New("issuer_uri is required")
	}

	return nil
}

// ValidateForCreate validates the entity for a create operation.
// skipHTTPSValidation allows HTTP URLs for development/testing.
// Does not require ID (will be generated by the domain service).
func (e *ThirdpartyOAuth2ProviderEntity) ValidateForCreate(skipHTTPSValidation bool) error {
	if e.DisplayName == "" {
		return errors.New("display_name is required")
	}
	if len(e.DisplayName) > 255 {
		return fmt.Errorf("display_name exceeds 255 characters (got %d)", len(e.DisplayName))
	}
	if e.ClientID == "" {
		return errors.New("client_id is required")
	}

	// Secret must be in plaintext for create (before encryption)
	if !e.Secret.IsPlaintext() {
		return errors.New("client_secret is required for create")
	}
	if _, err := e.Secret.GetPlaintext(); err != nil {
		return fmt.Errorf("client_secret is invalid: %w", err)
	}

	if e.IssuerURI == "" {
		return errors.New("issuer_uri is required")
	}
	if !isAllowedHTTPSScheme(e.IssuerURI, skipHTTPSValidation) {
		return errors.New("issuer_uri must be a valid HTTPS URL (HTTP allowed only for localhost in dev mode)")
	}

	if !e.Discovery.EnableDiscovery {
		if e.Endpoints.TokenEndpoint == "" {
			return errors.New("token_endpoint is required when discovery is disabled")
		}
		if e.Endpoints.AuthorizeEndpoint == "" {
			return errors.New("authorize_endpoint is required when discovery is disabled")
		}
	}

	if e.Discovery.MetadataURL != nil {
		if !isAllowedHTTPSScheme(*e.Discovery.MetadataURL, skipHTTPSValidation) {
			return errors.New("metadata_url must be a valid HTTPS URL (HTTP allowed only for localhost in dev mode)")
		}
	}

	if len(e.Scopes) == 0 {
		return errors.New("at least one scope is required")
	}
	for i, scope := range e.Scopes {
		if err := scope.Validate(); err != nil {
			return fmt.Errorf("scope %d: %w", i, err)
		}
	}

	return nil
}

// ValidateForUpdate validates the entity for an update operation.
// skipHTTPSValidation allows HTTP URLs for development/testing.
// Requires ID and plaintext Secret (callers must always supply the new secret in plaintext).
func (e *ThirdpartyOAuth2ProviderEntity) ValidateForUpdate(skipHTTPSValidation bool) error {
	if e.ID == "" {
		return errors.New("provider ID cannot be empty")
	}
	if e.DisplayName == "" {
		return errors.New("display_name is required")
	}
	if len(e.DisplayName) > 255 {
		return fmt.Errorf("display_name exceeds 255 characters (got %d)", len(e.DisplayName))
	}
	if e.ClientID == "" {
		return errors.New("client_id is required")
	}

	// Secret must be in plaintext for update (will be re-encrypted by the domain service).
	// Passing an already-encrypted secret is rejected to prevent silent bypass of re-encryption
	// (e.g. during key rotation) and to enforce a single, predictable Update contract.
	if !e.Secret.IsPlaintext() {
		return errors.New("client_secret is required for update")
	}
	if _, err := e.Secret.GetPlaintext(); err != nil {
		return fmt.Errorf("client_secret is invalid: %w", err)
	}

	if e.IssuerURI == "" {
		return errors.New("issuer_uri is required")
	}
	if !isAllowedHTTPSScheme(e.IssuerURI, skipHTTPSValidation) {
		return errors.New("issuer_uri must be a valid HTTPS URL (HTTP allowed only for localhost in dev mode)")
	}

	if !e.Discovery.EnableDiscovery {
		if e.Endpoints.TokenEndpoint == "" {
			return errors.New("token_endpoint is required when discovery is disabled")
		}
		if e.Endpoints.AuthorizeEndpoint == "" {
			return errors.New("authorize_endpoint is required when discovery is disabled")
		}
	}

	if e.Discovery.MetadataURL != nil {
		if !isAllowedHTTPSScheme(*e.Discovery.MetadataURL, skipHTTPSValidation) {
			return errors.New("metadata_url must be a valid HTTPS URL (HTTP allowed only for localhost in dev mode)")
		}
	}

	if len(e.Scopes) == 0 {
		return errors.New("at least one scope is required")
	}
	for i, scope := range e.Scopes {
		if err := scope.Validate(); err != nil {
			return fmt.Errorf("scope %d: %w", i, err)
		}
	}

	return nil
}

// ValidateProtectedResources validates all protected resource URIs are valid absolute URLs.
// Protected resources are optional; an empty slice is valid.
func (e *ThirdpartyOAuth2ProviderEntity) ValidateProtectedResources() error {
	for i, resourceURI := range e.ProtectedResources {
		if resourceURI == "" {
			return fmt.Errorf("protected_resources[%d]: cannot be empty", i)
		}
		parsed, err := url.Parse(resourceURI)
		if err != nil {
			return fmt.Errorf("protected_resources[%d]: invalid URI: %w", i, err)
		}
		if parsed.Scheme == "" || parsed.Host == "" {
			return fmt.Errorf("protected_resources[%d]: must be an absolute URL with scheme and host", i)
		}
	}
	return nil
}

// RedactedCopy returns a deep copy of the entity with Secret replaced by a plaintext
// "REDACTED" value. Use for API responses and logs to comply with SR-003.
func (e *ThirdpartyOAuth2ProviderEntity) RedactedCopy() *ThirdpartyOAuth2ProviderEntity {
	if e == nil {
		return nil
	}
	c := e.Copy()
	c.Secret = NewPlaintextSecret("REDACTED")
	return c
}

// Copy creates a deep copy of the entity to prevent external mutation.
// The Secret is copied by value (immutable), with internal slices independently copied.
func (e *ThirdpartyOAuth2ProviderEntity) Copy() *ThirdpartyOAuth2ProviderEntity {
	if e == nil {
		return nil
	}

	result := &ThirdpartyOAuth2ProviderEntity{
		ID:          e.ID,
		DisplayName: e.DisplayName,
		ClientID:    e.ClientID,
		Secret:      e.Secret, // Value type; internal ciphertext slice independently copied by Secret
		IssuerURI:   e.IssuerURI,
		Discovery: DiscoveryConfig{
			EnableDiscovery: e.Discovery.EnableDiscovery,
		},
		Endpoints: OAuth2Endpoints{
			TokenEndpoint:     e.Endpoints.TokenEndpoint,
			AuthorizeEndpoint: e.Endpoints.AuthorizeEndpoint,
		},
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
	}

	// Deep copy optional MetadataURL pointer
	if e.Discovery.MetadataURL != nil {
		metadataURL := *e.Discovery.MetadataURL
		result.Discovery.MetadataURL = &metadataURL
	}

	// Deep copy slices
	if e.Scopes != nil {
		result.Scopes = make([]OAuthScope, len(e.Scopes))
		for i, scope := range e.Scopes {
			result.Scopes[i] = scope.Copy()
		}
	}

	if e.ProtectedResources != nil {
		result.ProtectedResources = make([]string, len(e.ProtectedResources))
		copy(result.ProtectedResources, e.ProtectedResources)
	}

	if e.ServiceRequirements != nil {
		result.ServiceRequirements = make([]ServiceRequirement, len(e.ServiceRequirements))
		for i, sr := range e.ServiceRequirements {
			result.ServiceRequirements[i] = sr.Copy()
		}
	}

	return result
}
